### ISSUE TITLE
To-do list (for tracking)

### ISSUE THREAD

**Issue by andy0130tw** [andy0130tw/quartz-connect-iq-sdk#1]
- [ ] Attach footnotes that are referenced under certain page
- [x] Adjust code highlighter for dark themes -- done 20241129 ([943242f](https://github.com/andy0130tw/quartz-connect-iq-sdk/commit/943242f638648c15d44e4620c457b2f9d2c11cc0))
- [ ] Identify links to API docs as outbound
- [ ] Review the page extractor for more reliable parsing
- [ ] Setup CI
- [ ] Adopt per-page CSS/JS resources

---

- [ ] TOC support (requiring rewriting the `toc` plugin for HTML
